/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateDiagnosisInput {
  'quality_status' : string,
  'image_url' : string,
  'treatment' : string,
  'pesticide_recommendation' : string,
  'fertilizer_recommendation' : string,
  'notes' : string,
  'consult_expert' : boolean,
  'symptoms' : Array<string>,
  'severity' : Severity,
  'confidence' : bigint,
  'crop_name' : string,
  'disease_name' : string,
}
export interface CreateOrderInput {
  'total_amount' : number,
  'notes' : string,
  'delivery_address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export type CropCategory = { 'fiber' : null } |
  { 'fruit' : null } |
  { 'cereal' : null } |
  { 'other' : null } |
  { 'oilseed' : null } |
  { 'spice' : null } |
  { 'pulse' : null } |
  { 'vegetable' : null };
export interface CropDiagnosis {
  'id' : string,
  'quality_status' : string,
  'image_url' : string,
  'treatment' : string,
  'created_at' : Timestamp,
  'pesticide_recommendation' : string,
  'fertilizer_recommendation' : string,
  'user_id' : UserId,
  'notes' : string,
  'consult_expert' : boolean,
  'symptoms' : Array<string>,
  'severity' : Severity,
  'confidence' : bigint,
  'crop_name' : string,
  'disease_name' : string,
}
export type HealthStatus = { 'contaminated' : null } |
  { 'certified' : null } |
  { 'untreated' : null } |
  { 'treated' : null };
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total_amount' : number,
  'created_at' : Timestamp,
  'user_id' : UserId,
  'notes' : string,
  'delivery_address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'name' : string,
  'unit' : string,
  'quantity' : bigint,
  'price' : number,
  'pesticide_id' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Pesticide {
  'id' : string,
  'suitable_for' : Array<string>,
  'active_ingredient' : string,
  'image_url' : string,
  'name' : string,
  'unit' : string,
  'description' : string,
  'stock' : bigint,
  'category' : PesticideCategory,
  'is_available' : boolean,
  'brand' : string,
  'price' : number,
}
export type PesticideCategory = { 'biopesticide' : null } |
  { 'other' : null } |
  { 'herbicide' : null } |
  { 'rodenticide' : null } |
  { 'fungicide' : null } |
  { 'insecticide' : null };
export type QualityGrade = { 'a' : null } |
  { 'b' : null } |
  { 'c' : null } |
  { 'aplus' : null } |
  { 'rejected' : null };
export interface SeedBatch {
  'id' : string,
  'batch_number' : string,
  'manufacturer' : string,
  'certified_date' : bigint,
  'crop_category' : CropCategory,
  'quality_grade' : QualityGrade,
  'health_status' : HealthStatus,
  'germination_rate' : bigint,
  'seed_type' : string,
  'purity_percentage' : bigint,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'moderate' : null };
export type Timestamp = bigint;
export type UserId = string;
export interface _SERVICE {
  'createDiagnosis' : ActorMethod<[CreateDiagnosisInput], CropDiagnosis>,
  'createOrder' : ActorMethod<[CreateOrderInput], Order>,
  'deleteDiagnosis' : ActorMethod<[string], boolean>,
  'getDiagnosis' : ActorMethod<[string], [] | [CropDiagnosis]>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getPesticide' : ActorMethod<[string], [] | [Pesticide]>,
  'getSeedBatch' : ActorMethod<[string], [] | [SeedBatch]>,
  'listDiagnosesByUser' : ActorMethod<[], Array<CropDiagnosis>>,
  'listOrdersByUser' : ActorMethod<[], Array<Order>>,
  'listPesticides' : ActorMethod<[], Array<Pesticide>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];