/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'moderate' : IDL.Null,
});
export const CreateDiagnosisInput = IDL.Record({
  'quality_status' : IDL.Text,
  'image_url' : IDL.Text,
  'treatment' : IDL.Text,
  'pesticide_recommendation' : IDL.Text,
  'fertilizer_recommendation' : IDL.Text,
  'notes' : IDL.Text,
  'consult_expert' : IDL.Bool,
  'symptoms' : IDL.Vec(IDL.Text),
  'severity' : Severity,
  'confidence' : IDL.Nat,
  'crop_name' : IDL.Text,
  'disease_name' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Text;
export const CropDiagnosis = IDL.Record({
  'id' : IDL.Text,
  'quality_status' : IDL.Text,
  'image_url' : IDL.Text,
  'treatment' : IDL.Text,
  'created_at' : Timestamp,
  'pesticide_recommendation' : IDL.Text,
  'fertilizer_recommendation' : IDL.Text,
  'user_id' : UserId,
  'notes' : IDL.Text,
  'consult_expert' : IDL.Bool,
  'symptoms' : IDL.Vec(IDL.Text),
  'severity' : Severity,
  'confidence' : IDL.Nat,
  'crop_name' : IDL.Text,
  'disease_name' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'pesticide_id' : IDL.Text,
});
export const CreateOrderInput = IDL.Record({
  'total_amount' : IDL.Float64,
  'notes' : IDL.Text,
  'delivery_address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'total_amount' : IDL.Float64,
  'created_at' : Timestamp,
  'user_id' : UserId,
  'notes' : IDL.Text,
  'delivery_address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const PesticideCategory = IDL.Variant({
  'biopesticide' : IDL.Null,
  'other' : IDL.Null,
  'herbicide' : IDL.Null,
  'rodenticide' : IDL.Null,
  'fungicide' : IDL.Null,
  'insecticide' : IDL.Null,
});
export const Pesticide = IDL.Record({
  'id' : IDL.Text,
  'suitable_for' : IDL.Vec(IDL.Text),
  'active_ingredient' : IDL.Text,
  'image_url' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : PesticideCategory,
  'is_available' : IDL.Bool,
  'brand' : IDL.Text,
  'price' : IDL.Float64,
});
export const CropCategory = IDL.Variant({
  'fiber' : IDL.Null,
  'fruit' : IDL.Null,
  'cereal' : IDL.Null,
  'other' : IDL.Null,
  'oilseed' : IDL.Null,
  'spice' : IDL.Null,
  'pulse' : IDL.Null,
  'vegetable' : IDL.Null,
});
export const QualityGrade = IDL.Variant({
  'a' : IDL.Null,
  'b' : IDL.Null,
  'c' : IDL.Null,
  'aplus' : IDL.Null,
  'rejected' : IDL.Null,
});
export const HealthStatus = IDL.Variant({
  'contaminated' : IDL.Null,
  'certified' : IDL.Null,
  'untreated' : IDL.Null,
  'treated' : IDL.Null,
});
export const SeedBatch = IDL.Record({
  'id' : IDL.Text,
  'batch_number' : IDL.Text,
  'manufacturer' : IDL.Text,
  'certified_date' : IDL.Int,
  'crop_category' : CropCategory,
  'quality_grade' : QualityGrade,
  'health_status' : HealthStatus,
  'germination_rate' : IDL.Nat,
  'seed_type' : IDL.Text,
  'purity_percentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createDiagnosis' : IDL.Func([CreateDiagnosisInput], [CropDiagnosis], []),
  'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'deleteDiagnosis' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getDiagnosis' : IDL.Func([IDL.Text], [IDL.Opt(CropDiagnosis)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getPesticide' : IDL.Func([IDL.Text], [IDL.Opt(Pesticide)], ['query']),
  'getSeedBatch' : IDL.Func([IDL.Text], [IDL.Opt(SeedBatch)], ['query']),
  'listDiagnosesByUser' : IDL.Func([], [IDL.Vec(CropDiagnosis)], ['query']),
  'listOrdersByUser' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listPesticides' : IDL.Func([], [IDL.Vec(Pesticide)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const CreateDiagnosisInput = IDL.Record({
    'quality_status' : IDL.Text,
    'image_url' : IDL.Text,
    'treatment' : IDL.Text,
    'pesticide_recommendation' : IDL.Text,
    'fertilizer_recommendation' : IDL.Text,
    'notes' : IDL.Text,
    'consult_expert' : IDL.Bool,
    'symptoms' : IDL.Vec(IDL.Text),
    'severity' : Severity,
    'confidence' : IDL.Nat,
    'crop_name' : IDL.Text,
    'disease_name' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Text;
  const CropDiagnosis = IDL.Record({
    'id' : IDL.Text,
    'quality_status' : IDL.Text,
    'image_url' : IDL.Text,
    'treatment' : IDL.Text,
    'created_at' : Timestamp,
    'pesticide_recommendation' : IDL.Text,
    'fertilizer_recommendation' : IDL.Text,
    'user_id' : UserId,
    'notes' : IDL.Text,
    'consult_expert' : IDL.Bool,
    'symptoms' : IDL.Vec(IDL.Text),
    'severity' : Severity,
    'confidence' : IDL.Nat,
    'crop_name' : IDL.Text,
    'disease_name' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'pesticide_id' : IDL.Text,
  });
  const CreateOrderInput = IDL.Record({
    'total_amount' : IDL.Float64,
    'notes' : IDL.Text,
    'delivery_address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'total_amount' : IDL.Float64,
    'created_at' : Timestamp,
    'user_id' : UserId,
    'notes' : IDL.Text,
    'delivery_address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const PesticideCategory = IDL.Variant({
    'biopesticide' : IDL.Null,
    'other' : IDL.Null,
    'herbicide' : IDL.Null,
    'rodenticide' : IDL.Null,
    'fungicide' : IDL.Null,
    'insecticide' : IDL.Null,
  });
  const Pesticide = IDL.Record({
    'id' : IDL.Text,
    'suitable_for' : IDL.Vec(IDL.Text),
    'active_ingredient' : IDL.Text,
    'image_url' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : PesticideCategory,
    'is_available' : IDL.Bool,
    'brand' : IDL.Text,
    'price' : IDL.Float64,
  });
  const CropCategory = IDL.Variant({
    'fiber' : IDL.Null,
    'fruit' : IDL.Null,
    'cereal' : IDL.Null,
    'other' : IDL.Null,
    'oilseed' : IDL.Null,
    'spice' : IDL.Null,
    'pulse' : IDL.Null,
    'vegetable' : IDL.Null,
  });
  const QualityGrade = IDL.Variant({
    'a' : IDL.Null,
    'b' : IDL.Null,
    'c' : IDL.Null,
    'aplus' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const HealthStatus = IDL.Variant({
    'contaminated' : IDL.Null,
    'certified' : IDL.Null,
    'untreated' : IDL.Null,
    'treated' : IDL.Null,
  });
  const SeedBatch = IDL.Record({
    'id' : IDL.Text,
    'batch_number' : IDL.Text,
    'manufacturer' : IDL.Text,
    'certified_date' : IDL.Int,
    'crop_category' : CropCategory,
    'quality_grade' : QualityGrade,
    'health_status' : HealthStatus,
    'germination_rate' : IDL.Nat,
    'seed_type' : IDL.Text,
    'purity_percentage' : IDL.Nat,
  });
  
  return IDL.Service({
    'createDiagnosis' : IDL.Func([CreateDiagnosisInput], [CropDiagnosis], []),
    'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'deleteDiagnosis' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getDiagnosis' : IDL.Func([IDL.Text], [IDL.Opt(CropDiagnosis)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getPesticide' : IDL.Func([IDL.Text], [IDL.Opt(Pesticide)], ['query']),
    'getSeedBatch' : IDL.Func([IDL.Text], [IDL.Opt(SeedBatch)], ['query']),
    'listDiagnosesByUser' : IDL.Func([], [IDL.Vec(CropDiagnosis)], ['query']),
    'listOrdersByUser' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listPesticides' : IDL.Func([], [IDL.Vec(Pesticide)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };