/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateDiagnosisInput {
    quality_status: string;
    image_url: string;
    treatment: string;
    pesticide_recommendation: string;
    fertilizer_recommendation: string;
    notes: string;
    consult_expert: boolean;
    symptoms: Array<string>;
    severity: Severity;
    confidence: bigint;
    crop_name: string;
    disease_name: string;
}
export type Timestamp = bigint;
export interface OrderItem {
    name: string;
    unit: string;
    quantity: bigint;
    price: number;
    pesticide_id: string;
}
export interface Order {
    id: string;
    status: OrderStatus;
    total_amount: number;
    created_at: Timestamp;
    user_id: UserId;
    notes: string;
    delivery_address: string;
    phone: string;
    items: Array<OrderItem>;
}
export type UserId = string;
export interface CropDiagnosis {
    id: string;
    quality_status: string;
    image_url: string;
    treatment: string;
    created_at: Timestamp;
    pesticide_recommendation: string;
    fertilizer_recommendation: string;
    user_id: UserId;
    notes: string;
    consult_expert: boolean;
    symptoms: Array<string>;
    severity: Severity;
    confidence: bigint;
    crop_name: string;
    disease_name: string;
}
export interface Pesticide {
    id: string;
    suitable_for: Array<string>;
    active_ingredient: string;
    image_url: string;
    name: string;
    unit: string;
    description: string;
    stock: bigint;
    category: PesticideCategory;
    is_available: boolean;
    brand: string;
    price: number;
}
export interface CreateOrderInput {
    total_amount: number;
    notes: string;
    delivery_address: string;
    phone: string;
    items: Array<OrderItem>;
}
export interface SeedBatch {
    id: string;
    batch_number: string;
    manufacturer: string;
    certified_date: bigint;
    crop_category: CropCategory;
    quality_grade: QualityGrade;
    health_status: HealthStatus;
    germination_rate: bigint;
    seed_type: string;
    purity_percentage: bigint;
}
export enum CropCategory {
    fiber = "fiber",
    fruit = "fruit",
    cereal = "cereal",
    other = "other",
    oilseed = "oilseed",
    spice = "spice",
    pulse = "pulse",
    vegetable = "vegetable"
}
export enum HealthStatus {
    contaminated = "contaminated",
    certified = "certified",
    untreated = "untreated",
    treated = "treated"
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PesticideCategory {
    biopesticide = "biopesticide",
    other = "other",
    herbicide = "herbicide",
    rodenticide = "rodenticide",
    fungicide = "fungicide",
    insecticide = "insecticide"
}
export enum QualityGrade {
    a = "a",
    b = "b",
    c = "c",
    aplus = "aplus",
    rejected = "rejected"
}
export enum Severity {
    low = "low",
    high = "high",
    critical = "critical",
    moderate = "moderate"
}
export interface backendInterface {
    createDiagnosis(data: CreateDiagnosisInput): Promise<CropDiagnosis>;
    createOrder(data: CreateOrderInput): Promise<Order>;
    deleteDiagnosis(id: string): Promise<boolean>;
    getDiagnosis(id: string): Promise<CropDiagnosis | null>;
    getOrder(id: string): Promise<Order | null>;
    getPesticide(id: string): Promise<Pesticide | null>;
    getSeedBatch(batch_number: string): Promise<SeedBatch | null>;
    listDiagnosesByUser(): Promise<Array<CropDiagnosis>>;
    listOrdersByUser(): Promise<Array<Order>>;
    listPesticides(): Promise<Array<Pesticide>>;
}
import type { CreateDiagnosisInput as _CreateDiagnosisInput, CropCategory as _CropCategory, CropDiagnosis as _CropDiagnosis, HealthStatus as _HealthStatus, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Pesticide as _Pesticide, PesticideCategory as _PesticideCategory, QualityGrade as _QualityGrade, SeedBatch as _SeedBatch, Severity as _Severity, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createDiagnosis(arg0: CreateDiagnosisInput): Promise<CropDiagnosis> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiagnosis(to_candid_CreateDiagnosisInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CropDiagnosis_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiagnosis(to_candid_CreateDiagnosisInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CropDiagnosis_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: CreateOrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return from_candid_Order_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return from_candid_Order_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDiagnosis(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDiagnosis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDiagnosis(arg0);
            return result;
        }
    }
    async getDiagnosis(arg0: string): Promise<CropDiagnosis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiagnosis(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiagnosis(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPesticide(arg0: string): Promise<Pesticide | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPesticide(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPesticide(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeedBatch(arg0: string): Promise<SeedBatch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeedBatch(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeedBatch(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDiagnosesByUser(): Promise<Array<CropDiagnosis>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDiagnosesByUser();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDiagnosesByUser();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrdersByUser(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrdersByUser();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrdersByUser();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPesticides(): Promise<Array<Pesticide>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPesticides();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPesticides();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CropCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropCategory): CropCategory {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CropDiagnosis_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropDiagnosis): CropDiagnosis {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_HealthStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthStatus): HealthStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PesticideCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PesticideCategory): PesticideCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Pesticide_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pesticide): Pesticide {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_QualityGrade_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QualityGrade): QualityGrade {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SeedBatch_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeedBatch): SeedBatch {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CropDiagnosis]): CropDiagnosis | null {
    return value.length === 0 ? null : from_candid_CropDiagnosis_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pesticide]): Pesticide | null {
    return value.length === 0 ? null : from_candid_Pesticide_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SeedBatch]): SeedBatch | null {
    return value.length === 0 ? null : from_candid_SeedBatch_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    total_amount: number;
    created_at: _Timestamp;
    user_id: _UserId;
    notes: string;
    delivery_address: string;
    phone: string;
    items: Array<_OrderItem>;
}): {
    id: string;
    status: OrderStatus;
    total_amount: number;
    created_at: Timestamp;
    user_id: UserId;
    notes: string;
    delivery_address: string;
    phone: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n11(_uploadFile, _downloadFile, value.status),
        total_amount: value.total_amount,
        created_at: value.created_at,
        user_id: value.user_id,
        notes: value.notes,
        delivery_address: value.delivery_address,
        phone: value.phone,
        items: value.items
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    suitable_for: Array<string>;
    active_ingredient: string;
    image_url: string;
    name: string;
    unit: string;
    description: string;
    stock: bigint;
    category: _PesticideCategory;
    is_available: boolean;
    brand: string;
    price: number;
}): {
    id: string;
    suitable_for: Array<string>;
    active_ingredient: string;
    image_url: string;
    name: string;
    unit: string;
    description: string;
    stock: bigint;
    category: PesticideCategory;
    is_available: boolean;
    brand: string;
    price: number;
} {
    return {
        id: value.id,
        suitable_for: value.suitable_for,
        active_ingredient: value.active_ingredient,
        image_url: value.image_url,
        name: value.name,
        unit: value.unit,
        description: value.description,
        stock: value.stock,
        category: from_candid_PesticideCategory_n18(_uploadFile, _downloadFile, value.category),
        is_available: value.is_available,
        brand: value.brand,
        price: value.price
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    batch_number: string;
    manufacturer: string;
    certified_date: bigint;
    crop_category: _CropCategory;
    quality_grade: _QualityGrade;
    health_status: _HealthStatus;
    germination_rate: bigint;
    seed_type: string;
    purity_percentage: bigint;
}): {
    id: string;
    batch_number: string;
    manufacturer: string;
    certified_date: bigint;
    crop_category: CropCategory;
    quality_grade: QualityGrade;
    health_status: HealthStatus;
    germination_rate: bigint;
    seed_type: string;
    purity_percentage: bigint;
} {
    return {
        id: value.id,
        batch_number: value.batch_number,
        manufacturer: value.manufacturer,
        certified_date: value.certified_date,
        crop_category: from_candid_CropCategory_n23(_uploadFile, _downloadFile, value.crop_category),
        quality_grade: from_candid_QualityGrade_n25(_uploadFile, _downloadFile, value.quality_grade),
        health_status: from_candid_HealthStatus_n27(_uploadFile, _downloadFile, value.health_status),
        germination_rate: value.germination_rate,
        seed_type: value.seed_type,
        purity_percentage: value.purity_percentage
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    quality_status: string;
    image_url: string;
    treatment: string;
    created_at: _Timestamp;
    pesticide_recommendation: string;
    fertilizer_recommendation: string;
    user_id: _UserId;
    notes: string;
    consult_expert: boolean;
    symptoms: Array<string>;
    severity: _Severity;
    confidence: bigint;
    crop_name: string;
    disease_name: string;
}): {
    id: string;
    quality_status: string;
    image_url: string;
    treatment: string;
    created_at: Timestamp;
    pesticide_recommendation: string;
    fertilizer_recommendation: string;
    user_id: UserId;
    notes: string;
    consult_expert: boolean;
    symptoms: Array<string>;
    severity: Severity;
    confidence: bigint;
    crop_name: string;
    disease_name: string;
} {
    return {
        id: value.id,
        quality_status: value.quality_status,
        image_url: value.image_url,
        treatment: value.treatment,
        created_at: value.created_at,
        pesticide_recommendation: value.pesticide_recommendation,
        fertilizer_recommendation: value.fertilizer_recommendation,
        user_id: value.user_id,
        notes: value.notes,
        consult_expert: value.consult_expert,
        symptoms: value.symptoms,
        severity: from_candid_Severity_n7(_uploadFile, _downloadFile, value.severity),
        confidence: value.confidence,
        crop_name: value.crop_name,
        disease_name: value.disease_name
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    biopesticide: null;
} | {
    other: null;
} | {
    herbicide: null;
} | {
    rodenticide: null;
} | {
    fungicide: null;
} | {
    insecticide: null;
}): PesticideCategory {
    return "biopesticide" in value ? PesticideCategory.biopesticide : "other" in value ? PesticideCategory.other : "herbicide" in value ? PesticideCategory.herbicide : "rodenticide" in value ? PesticideCategory.rodenticide : "fungicide" in value ? PesticideCategory.fungicide : "insecticide" in value ? PesticideCategory.insecticide : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fiber: null;
} | {
    fruit: null;
} | {
    cereal: null;
} | {
    other: null;
} | {
    oilseed: null;
} | {
    spice: null;
} | {
    pulse: null;
} | {
    vegetable: null;
}): CropCategory {
    return "fiber" in value ? CropCategory.fiber : "fruit" in value ? CropCategory.fruit : "cereal" in value ? CropCategory.cereal : "other" in value ? CropCategory.other : "oilseed" in value ? CropCategory.oilseed : "spice" in value ? CropCategory.spice : "pulse" in value ? CropCategory.pulse : "vegetable" in value ? CropCategory.vegetable : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    a: null;
} | {
    b: null;
} | {
    c: null;
} | {
    aplus: null;
} | {
    rejected: null;
}): QualityGrade {
    return "a" in value ? QualityGrade.a : "b" in value ? QualityGrade.b : "c" in value ? QualityGrade.c : "aplus" in value ? QualityGrade.aplus : "rejected" in value ? QualityGrade.rejected : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contaminated: null;
} | {
    certified: null;
} | {
    untreated: null;
} | {
    treated: null;
}): HealthStatus {
    return "contaminated" in value ? HealthStatus.contaminated : "certified" in value ? HealthStatus.certified : "untreated" in value ? HealthStatus.untreated : "treated" in value ? HealthStatus.treated : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    moderate: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "critical" in value ? Severity.critical : "moderate" in value ? Severity.moderate : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CropDiagnosis>): Array<CropDiagnosis> {
    return value.map((x)=>from_candid_CropDiagnosis_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pesticide>): Array<Pesticide> {
    return value.map((x)=>from_candid_Pesticide_n16(_uploadFile, _downloadFile, x));
}
function to_candid_CreateDiagnosisInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDiagnosisInput): _CreateDiagnosisInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quality_status: string;
    image_url: string;
    treatment: string;
    pesticide_recommendation: string;
    fertilizer_recommendation: string;
    notes: string;
    consult_expert: boolean;
    symptoms: Array<string>;
    severity: Severity;
    confidence: bigint;
    crop_name: string;
    disease_name: string;
}): {
    quality_status: string;
    image_url: string;
    treatment: string;
    pesticide_recommendation: string;
    fertilizer_recommendation: string;
    notes: string;
    consult_expert: boolean;
    symptoms: Array<string>;
    severity: _Severity;
    confidence: bigint;
    crop_name: string;
    disease_name: string;
} {
    return {
        quality_status: value.quality_status,
        image_url: value.image_url,
        treatment: value.treatment,
        pesticide_recommendation: value.pesticide_recommendation,
        fertilizer_recommendation: value.fertilizer_recommendation,
        notes: value.notes,
        consult_expert: value.consult_expert,
        symptoms: value.symptoms,
        severity: to_candid_Severity_n3(_uploadFile, _downloadFile, value.severity),
        confidence: value.confidence,
        crop_name: value.crop_name,
        disease_name: value.disease_name
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    moderate: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.critical ? {
        critical: null
    } : value == Severity.moderate ? {
        moderate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
